config/routes.rb
Rails.application.routes.draw do

  resources :decks do
    resources :cards, except: :index
  end

  root "decks#index"

end

app/models/card.rb
class Card < ActiveRecord::Base
  belongs_to :deck
end

app/models/deck.rb
class Deck < ActiveRecord::Base
  # reverse of belongs_to, provides Deck.cards()
  has_many :cards
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  def show
    @card = Card.find(params[:id])
    @deck = @card.deck
  end
end

app/controllers/decks_controller.rb
class DecksController < ApplicationController
  # this is an 'action' rather than a 'method' because it is
  # accessible through a route
  def index
    @decks = Deck.all
  end

  def show
    @deck = Deck.find(params[:id])
    @cards = @deck.cards
  end

  def new
    @deck = Deck.new
  end

  def create
    @deck = Deck.new(deck_params)
    @deck.save
    # redirect_to deck_path(@deck) ===
    redirect_to @deck
  end

  def edit
    @deck = Deck.find(params[:id])
  end

  def update
    @deck = Deck.find(params[:id])
    @deck.update_attributes(deck_params)
    @deck.save
    # redirect_to deck_path(@deck) ===
    redirect_to @deck
  end

  def destroy
    @deck = Deck.find(params[:id])
    @deck.destroy
    redirect_to decks_path
  end

  private
  def deck_params
    params.require(:deck).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cards/show.html.erb
<h1><%= link_to @deck.name, @deck %></h1>
<h2><%= @card.front %> = <%= @card.back %></h2>

app/views/decks/edit.html.erb
<h1>Edit <%= @deck.name %></h1>

<%= form_for @deck do |f| %>
  <ul>
    <li>
      <%= f.label :name %>
      <%= f.text_field :name %>
    </li>
  </ul>
  <%= f.submit "Save changes" %>
<% end %>

app/views/decks/index.html.erb
<h1>meow</h1>

<%= link_to "new", new_deck_path %>

<ul>
<% @decks.each do |deck| %>
  <li>
    <%= link_to deck.name, deck %><!-- == deck_path(deck) -->
    -
    <%= link_to "edit", edit_deck_path(deck) %>
    <%= link_to "delete", deck, :method => "delete", :data => { :confirm => "Are you sure?" } %>
  </li>
<% end %>
</ul>

app/views/decks/new.html.erb
<h1>Create something new yay</h1>

<%= form_for @deck do |f| %>
  <ul>
    <li>
      <%= f.label :name %>
      <%= f.text_field :name %>
    </li>
  </ul>
  <%= f.submit "Create deck" %>
<% end %>

app/views/decks/show.html.erb
<%= link_to "Decks", decks_path %>

<h1><%= @deck.name %></h1>

<%= link_to "Edit", edit_deck_path(@deck) %>
<%= link_to "Delete", deck_path(@deck), :method => "delete", :data => {:confirm => "Are you sure?"} %>

Created at <%= @deck.created_at %>

<ul>
<% @cards.each do |card| %>
  <li><%= link_to card.front, [card.deck, card] %></li>
<% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Flashcards</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>